# top
templates: []
mode: train
pilot: false
pretrained_weights: null
num_users: null
num_items: null
num_interactions: null
local_data_folder: ./data
experiment_root: ./experiments
experiment_group: test
experiment_name: null
# dataset
dataset_type: ml-1m
use_negatives: False
eval_type: leave_positive_out
# dataloader
dataloader_type: temp
dataloader_random_seed: 0.0
train_batch_size: 256
val_batch_size: 256
test_batch_size: 256
max_seq_len: 100
# negative_sampler
train_negative_sampler_code: random
train_negative_sample_size: 0
train_negative_sampling_seed: 0
test_negative_sampler_code: popular
test_negative_sample_size: 100
test_negative_sampling_seed: 98765
# trainer
trainer_type: im
device: cuda
use_parallel: true
num_workers: 0
optimizer: adam
lr: 0.001
weight_decay: 0.0
momentum: null
decay_step: 25
gamma: 1.0
clip_grad_norm: 5.0
num_epochs: 100
log_period_as_iter: 12800
metric_ks:
- 1
- 5
- 10
- 20
- 50
best_metric: NDCG@10
# model
model_type: sasrec
model_init_seed: 0
model_init_range: 0.02
max_len: 200
hidden_units: 64
num_blocks: 2
num_heads: 2
dropout: 0.2
output_info: false
headtype: dot
head_use_ln: false
wandb_project_name: null
wandb_run_name: null
wandb_run_id: null