# top
templates: []
mode: train
seed: 0
pilot: false
pretrained_weights: null
num_users: null
num_items: null
num_ratings: null
num_interactions: null
local_data_folder: ./data
wandb_project_name: bcq4rec
exp_name: test
# dataset
dataset_type: eachmovie
min_rating: 4
min_uc: 5
min_sc: 5
eval_type: split_users
train_ratio: 0.85
val_ratio: 0.05
test_ratio: 0.1
# dataloader
dataloader_type: sequential
train_batch_size: 256
val_batch_size: 256
test_batch_size: 256
max_seq_len: 200
window_size: 100
# negative_sampler
train_negative_sampler_code: popular
train_negative_sample_size: 256
train_negative_sampling_seed: 98765
test_negative_sampler_code: popular
test_negative_sample_size: 100
test_negative_sampling_seed: 98765
# trainer
trainer_type: nip
device: cuda
use_parallel: false
num_workers: 4  # larger number of workers induce higher i/o bottleneck
optimizer: adam
lr: 0.01
weight_decay: 0.0001
momentum: null
clip_grad_norm: 5.0
dropout: 0.1
num_epochs: 100
log_period_as_iter: 12800
metric_ks:
- 1
- 5
- 10
- 20
best_metric: NDCG@10
# model
model_type: sas
model_init_seed: 0
hidden_units: 64
num_blocks: 2
num_heads: 2
output_info: false
head_type: dot
# env
env_type: rating
reward_model_dir: sas_block2_d64
num_cold_start: 5
num_warm_start: 40
metric_ts:
- 1
- 5
- 10
- 20
- 40